config/routes.rb
Rails.application.routes.draw do
  resources :notes
  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  has_secure_token
  extend FriendlyId
  friendly_id :token, use: :slugged

  validates_presence_of :user
  validates_presence_of :description
  validates_presence_of :token
  validates_uniqueness_of :token

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :notes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :index]
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = current_user.notes.order(:created_at => 'DESC').page(params[:page]).per(6)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    authorize @note
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.new(note_params)
    @note.token = SecureRandom.hex(10).upcase
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    authorize @note
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    authorize @note
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      #@note = Note.friendly.find(params[:id])
      @note = Note.find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to notes_path
    end
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <script>
$(document).ready(function(){
      Materialize.toast('#{messages}', 6000, 'rounded');
});
    </script>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <title><%= yield :title %>Key-Note</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render partial: 'shared/header' %>

<main>
  <%= yield %>
</main>

<%= render partial: 'shared/footer' %>

<script>
    $(document).ready(function(){
        <% flash.each do |type, message| %>
        Materialize.toast('<%= message %>', 3000, 'rounded');
    <% end %>
    });
</script>
</body>
</html>

app/views/notes/_form.html.erb
<%= tinymce_assets %>
<%= tinymce %>
<%= form_for(@note) do |f| %>

    <div class="row">
      <div class="input-field col s12">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, input_html: {class: "validate"} %>
      </div>
    </div>

    <div class="row">
      <div class="input-field col s12">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'tinymce', :rows => 40, :cols => 120 %>
      </div>
    </div>

    <div class="card-action">
      <%= link_to '<i class="mdi-content-backspace left"></i> Back'.html_safe, notes_path, class: 'waves-effect waves-light btn red darken-4 white-text' %>
      <%= button_tag(type: 'submit', class: "waves-effect waves-light btn light-green darken-4") do %>
          Submit <i class="mdi-content-send right"></i>
      <% end %>
    </div>
<% end %>

<script>
    <% if @note.errors.any? %>
    <% @note.errors.full_messages.each do |message| %>
    Materialize.toast('<li><%= message %></li>', 6000, 'rounded');
    <% end %>
    <% end %>
</script>

app/views/notes/_note.html.erb
<div class="col s12 m6 l4">
  <div class="card-panel grey lighten-5 z-depth-3">
    <div class="card-content grey-text">
      <span class="card-title black-text"><%= note.title %></span><span class="right"><%= time_ago_in_words(note.created_at) %> ago</span>
      <p><%= note.description.truncate(50).html_safe %></p>
    </div>
    <div class="card-action">
      <%= link_to '<i class="mdi-image-remove-red-eye"></i>'.html_safe, note, class: "waves-effect waves-dark btn grey lighter-1 black-text" %>
      <% if user_signed_in? && note.user == current_user %>
          <%= link_to '<i class="mdi-editor-mode-edit"></i>'.html_safe, edit_note_path(note), class: "waves-effect waves-dark btn blue darker-1 white-text", 'data-no-turbolink' => true %>
          <%= link_to '<i class="mdi-action-delete"></i>'.html_safe, note, method: :delete, data: { confirm: 'Are you sure?' }, class: "waves-effect waves-dark btn red darker-1 white-text" %>
      <% end %>
    </div>
  </div>
</div>

app/views/notes/edit.html.erb
<% content_for :title do %>
    Edit |
<% end %>
<div class="row">
  <div class="col s12 m10 offset-m1 l8 offset-l2">
    <div class="card grey lighten-5 z-depth-5">
      <div class="card-content black-text">
        <span class="card-title black-text">Edit Key-Note</span>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<div class="row">
  <div class="col s12 m6 offset-m3">
    <div class="card-panel grey lighten-5">
      <h6 class="black-text flow-text center-align">Key-Notes</h6>
    </div>
  </div>
</div>
<div class="row">
    <%= render @notes %>
</div>
    <%= paginate @notes %>
<div class="fixed-action-btn" style="bottom: 45px; right: 24px;">
  <%= link_to '<i class="mdi-content-add"></i>'.html_safe, new_note_path, class:"btn-floating btn-large waves-effect waves-light red", 'data-no-turbolink' => true %>
</div>

app/views/notes/new.html.erb
<% content_for :title do %>
    New |
<% end %>
<div class="row">
  <div class="col s12 m10 offset-m1 l8 offset-l2">
    <div class="card grey lighten-5 z-depth-5">
      <div class="card-content black-text">
        <span class="card-title black-text">New Key-Note</span>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/notes/show.html.erb
<% content_for :title do %>
    <%= @note.title %> |
<% end %>
<div class="row">
  <div class="col s12 m10 offset-m1 l8 offset-l2">
    <div class="card grey lighten-5 z-depth-5">
      <div class="card-content black-text">
        <span class="card-title black-text"><%= @note.title %></span><a class="waves-effect waves-light btn modal-trigger white-text right" href="#modal1"><i class="mdi-social-share left"></i>Share</a>
        <div class="row">
          <div class="col s12">
            <%= @note.description.html_safe %>
            <p class="right grey-text">Created by: <%= @note.user.email %></p><br>
            <p class="right grey-text"><%= time_ago_in_words(@note.created_at) %> ago</p>
          </div>
        </div>
        <div class="card-action">
          <%= link_to '<i class="mdi-content-backspace left"></i>Back'.html_safe, root_path, class: 'waves-effect waves-light btn red darken-4 white-text' %>
          <% if user_signed_in? && @note.user == current_user %>
              <%= link_to '<i class="mdi-editor-mode-edit left"></i>Edit'.html_safe, edit_note_path(@note), class: 'waves-effect waves-light btn blue darken-4 white-text' %>
          <% end %>
          <!-- Modal Trigger -->

          <!-- Modal Structure -->
          <div id="modal1" class="modal">
            <div class="modal-content">
              <h4>Shareable Link</h4>
              <p>Your share link is below: (click copy to automatically copy link)</p>
              <div class="row">
                <div class="input-field col s12">
                  <input value="<%= note_url(@note) %>" id="fe_text" type="text" class="validate">
                  <label class="active" for="fe_text">URL</label>
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <a href="" data-clipboard-target='fe_text' data-clipboard-text='Default clipboard text from attribute' id='d_clip_button' class=" modal-action modal-close waves-effect waves-light btn white-text right"><i class="mdi-content-content-copy left"></i> Copy Link To Clipboard</a>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>
<script>
    $(document).ready(function(){
// the "href" attribute of .modal-trigger must specify the modal ID that wants to be triggered
        $('.modal-trigger').leanModal();
        var clip = new ZeroClipboard($("a#d_clip_button"))
        clip.on( 'aftercopy', function(event) {
        } );
    });
</script>

app/views/pages/about.html.erb
<% content_for :title do %>
    About |
<% end %>
<div class="row">
  <div class="col m8 offset-m2">
    <div class="card grey lighten-2 z-depth-2">
          <span class="black-text flow-text">This app is about taking and saving notes from user and keep them safe until they share.
            This is a test project made by <a href="http://sulmanbaig.com">Sulman Baig</a>
          </span>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<% content_for :title do %>
    Home |
<% end %>
<div class="section white">
  <div class="row container">
    <h2 class="header">Key-Note</h2>
    <p class="grey-text text-darken-3 lighten-3 flow-text">Take notes online in HTML5 way and save and share with every-one.</p>
    <p><%= link_to '<i class="mdi-social-person-add left"></i> Sign Up'.html_safe, new_user_registration_path, class: 'waves-effect waves-light btn-large light-blue darken-4' %>
      <%= link_to '<i class="mdi-social-person left"></i> Log In'.html_safe, new_user_session_path, class: 'waves-effect waves-light btn-large light-green darken-4' %></p>
  </div>
</div>
<div class="parallax-container">
  <div class="parallax"><%= image_tag 'parallax2.jpg' %></div>
</div>
<!--<div class="parallax-container">-->
  <!--<div class="parallax"><%= image_tag 'parallax2.jpg' %></div>-->
<!--</div>-->

<script>
    $(document).ready(function(){
        $('.parallax').parallax();
    });
</script>

app/views/shared/_footer.html.erb
<footer class="page-footer grey darken-2 z-depth-2">
  <div class="container">
    <div class="row">
    <a class="grey-text text-lighten-4 right" href="http://sulmanbaig.com">&copy; Copyright Sulman Baig </a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <!-- Dropdown Structure -->
  <ul id="dropdown1" class="dropdown-content">
    <li><%= link_to '<i class="mdi-action-settings left"></i> Settings'.html_safe, edit_user_registration_path %></li>
    <li class="divider"></li>
    <li><%= link_to '<i class="mdi-social-person-outline left"></i> Log Out'.html_safe, destroy_user_session_path, method: :delete %></li>
  </ul>
  <!-- Dropdown Structure -->
  <ul id="dropdown2" class="dropdown-content">
    <li><%= link_to '<i class="mdi-action-settings left"></i> Settings'.html_safe, edit_user_registration_path %></li>
    <li class="divider"></li>
    <li><%= link_to '<i class="mdi-social-person-outline left"></i> Log Out'.html_safe, destroy_user_session_path, method: :delete %></li>
  </ul>


  <div class="navbar-fixed">
    <nav class="grey darken-2 z-depth-2">
      <div class="nav-wrapper">
        <%= link_to '<i class="mdi-action-assignment left"></i>Key-Note'.html_safe, root_path, class: "brand-logo" %>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
        <ul class="right hide-on-med-and-down">
          <% if !user_signed_in? %>
              <li><%= link_to '<i class="mdi-action-info left"></i> Info'.html_safe, about_path  %></li>
              <li><%= link_to '<i class="mdi-social-person left"></i> Log In'.html_safe, new_user_session_path %></li>
          <% else %>
              <li><%= link_to '<i class="mdi-action-assignment left"></i> My Key-Notes'.html_safe, notes_path  %></li>
              <!-- Dropdown Trigger -->
              <li><a class="dropdown-button" href="#!" data-activates="dropdown1"><i class="mdi-social-person left"></i> <%= current_user.email %><i class="mdi-navigation-arrow-drop-down right"></i></a></li>
          <% end %>
        </ul>
        <ul class="side-nav" id="mobile-demo">
          <% if !user_signed_in? %>
              <li><%= link_to '<i class="mdi-action-info left"></i> Info'.html_safe, about_path  %></li>
              <li><%= link_to '<i class="mdi-social-person left"></i> Log In'.html_safe, new_user_session_path %></li>
          <% else %>
              <li><%= link_to '<i class="mdi-action-assignment left"></i> My Key-Notes'.html_safe, notes_path  %></li>
              <li><a class="dropdown-button" href="#!" data-activates="dropdown2"><i class="mdi-social-person left"></i> User<i class="mdi-navigation-arrow-drop-down right"></i></a></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

<script>
    $(document).ready(function(){
        $(".button-collapse").sideNav();
        $(".dropdown-button").dropdown();
    });
</script>